/*
--------------------------------------------------------------------------------------
-- - Name          : TEST_SMC_AP_ManageQuoteLineItem
-- - Author        : DOS
-- - Description   : Manage Quote Line Item               
-- Maintenance History:
--
-- Date         Name                Version  Remarks
-- -----------  ----                -------  -----------------------------------------
-- 11-OCT-19    David SOBCZAK    	1.0     Initial version
--------------------------------------------------------------------------------------
*/

@isTest
public with sharing class TEST_SMC_AP_ManageQuoteLineItem {
  // @testSetup
  // public static void setup() {
  // }

  /**
   * @description : TODO
   * @author Vincent RECASENS (Modis) | 07-15-2020
   **/
  @isTest
  public static void preventDeleteByUI() {
    System.assert(true, 'The function assert is broken.');
  }
}